# Generated by Django 6.0.5 on 2026-06-01 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(unique=True)),
                ('station_name', models.CharField(max_length=150)),
                ('province', models.CharField(max_length=50)),
                ('climate_identifier', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('elevation', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('first_year', models.IntegerField(blank=True, null=True)),
                ('last_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weather Station',
                'verbose_name_plural': 'Weather Stations',
                'ordering': ['province', 'station_name'],
                'indexes': [models.Index(fields=['station_id'], name='weather_loc_station_739b3f_idx'), models.Index(fields=['province'], name='weather_loc_provinc_a9bc81_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateField()),
                ('max_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mean_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_rain', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_snow', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_precipitation', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='weather.location')),
            ],
            options={
                'verbose_name': 'Weather Record',
                'verbose_name_plural': 'Weather Records',
                'ordering': ['-recorded_date'],
                'indexes': [models.Index(fields=['recorded_date'], name='weather_wea_recorde_ab180c_idx'), models.Index(fields=['location'], name='weather_wea_locatio_b68e5e_idx')],
                'constraints': [models.UniqueConstraint(fields=('location', 'recorded_date'), name='unique_station_daily_record')],
            },
        ),
    ]
