# Generated by Django 6.0.5 on 2026-06-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherrecord',
            name='max_wind_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='weatherrecord',
            name='snow_on_ground',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='weatherrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='weatherrecord',
            name='weather_condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
