# Generated by Django 6.0.5 on 2026-06-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatherrecord_max_wind_speed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherrecord',
            options={'ordering': ['-recorded_date']},
        ),
        migrations.RemoveIndex(
            model_name='weatherrecord',
            name='weather_wea_recorde_ab180c_idx',
        ),
        migrations.RemoveIndex(
            model_name='weatherrecord',
            name='weather_wea_locatio_b68e5e_idx',
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='max_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='max_wind_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='mean_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='min_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='snow_on_ground',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='total_precipitation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='total_rain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='total_snow',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.RemoveField(
            model_name='weatherrecord',
            name='weather_condition',
        ),
    ]
